name: Update Cloaking Rules

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  update-cloaking-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download hosts file
      run: |
        curl -o hosts https://raw.githubusercontent.com/ImMALWARE/dns.malw.link/refs/heads/master/hosts

    - name: Process hosts file
      run: |
        sed 's/#.*$//' hosts | \
        grep -v '^\s*#' | \
        grep -v '0\.0\.0\.0' | \
        grep -v '^\s*$' | \
        awk '{print $2 " " $1}' > cloaking-rules.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add cloaking-rules.txt
        git commit -m "Update cloaking-rules.txt with latest processed hosts" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
